### ISSUE TITLE
[FR] Remove reopen crashed tabs popup

### ISSUE THREAD

**Issue by pallavagarwal07** [googleinterns/aso_sxs_viewer#11]
I see in the shared video that the crashed tabs bubble is still coming up. To remove that, you can edit the <session_path>/dir1/Default/Preferences file (one per browser) to set "exit_type":"Normal","exited_cleanly":true (only if the file already exists) just before you launch the browser.

**Comment by leshnabalara** [comment]
Closed by Pull Request #20
